# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rheingoldgraph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rheingoldgraph.proto.music_pb2 as music__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rheingoldgraph.proto',
  package='rheingoldgraph',
  syntax='proto3',
  serialized_pb=_b('\n\x14rheingoldgraph.proto\x12\x0erheingoldgraph\x1a\x0bmusic.proto\"\x1e\n\x0eSummaryRequest\x12\x0c\n\x04line\x18\x01 \x01(\t\"\x1b\n\x0bLineRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"z\n\x0cGraphSummary\x12\x16\n\x0etotal_vertices\x18\x01 \x01(\x05\x12\x13\n\x0btotal_edges\x18\x02 \x01(\x05\x12\x11\n\tnum_lines\x18\x03 \x01(\x05\x12*\n\x05lines\x18\x04 \x03(\x0b\x32\x1b.rheingoldgraph.LineSummary\"-\n\x0bLineSummary\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08vertices\x18\x02 \x01(\x05\x32\xac\x01\n\x0eRheingoldGraph\x12L\n\nGetSummary\x12\x1e.rheingoldgraph.SummaryRequest\x1a\x1c.rheingoldgraph.GraphSummary\"\x00\x12L\n\x0fGetPlayableLine\x12\x1b.rheingoldgraph.LineRequest\x1a\x18.tensorflow.magenta.Note\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[music__pb2.DESCRIPTOR,])




_SUMMARYREQUEST = _descriptor.Descriptor(
  name='SummaryRequest',
  full_name='rheingoldgraph.SummaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='rheingoldgraph.SummaryRequest.line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=83,
)


_LINEREQUEST = _descriptor.Descriptor(
  name='LineRequest',
  full_name='rheingoldgraph.LineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rheingoldgraph.LineRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=112,
)


_GRAPHSUMMARY = _descriptor.Descriptor(
  name='GraphSummary',
  full_name='rheingoldgraph.GraphSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_vertices', full_name='rheingoldgraph.GraphSummary.total_vertices', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_edges', full_name='rheingoldgraph.GraphSummary.total_edges', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_lines', full_name='rheingoldgraph.GraphSummary.num_lines', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lines', full_name='rheingoldgraph.GraphSummary.lines', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=236,
)


_LINESUMMARY = _descriptor.Descriptor(
  name='LineSummary',
  full_name='rheingoldgraph.LineSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rheingoldgraph.LineSummary.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='rheingoldgraph.LineSummary.vertices', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=283,
)

_GRAPHSUMMARY.fields_by_name['lines'].message_type = _LINESUMMARY
DESCRIPTOR.message_types_by_name['SummaryRequest'] = _SUMMARYREQUEST
DESCRIPTOR.message_types_by_name['LineRequest'] = _LINEREQUEST
DESCRIPTOR.message_types_by_name['GraphSummary'] = _GRAPHSUMMARY
DESCRIPTOR.message_types_by_name['LineSummary'] = _LINESUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SummaryRequest = _reflection.GeneratedProtocolMessageType('SummaryRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMMARYREQUEST,
  __module__ = 'rheingoldgraph_pb2'
  # @@protoc_insertion_point(class_scope:rheingoldgraph.SummaryRequest)
  ))
_sym_db.RegisterMessage(SummaryRequest)

LineRequest = _reflection.GeneratedProtocolMessageType('LineRequest', (_message.Message,), dict(
  DESCRIPTOR = _LINEREQUEST,
  __module__ = 'rheingoldgraph_pb2'
  # @@protoc_insertion_point(class_scope:rheingoldgraph.LineRequest)
  ))
_sym_db.RegisterMessage(LineRequest)

GraphSummary = _reflection.GeneratedProtocolMessageType('GraphSummary', (_message.Message,), dict(
  DESCRIPTOR = _GRAPHSUMMARY,
  __module__ = 'rheingoldgraph_pb2'
  # @@protoc_insertion_point(class_scope:rheingoldgraph.GraphSummary)
  ))
_sym_db.RegisterMessage(GraphSummary)

LineSummary = _reflection.GeneratedProtocolMessageType('LineSummary', (_message.Message,), dict(
  DESCRIPTOR = _LINESUMMARY,
  __module__ = 'rheingoldgraph_pb2'
  # @@protoc_insertion_point(class_scope:rheingoldgraph.LineSummary)
  ))
_sym_db.RegisterMessage(LineSummary)



_RHEINGOLDGRAPH = _descriptor.ServiceDescriptor(
  name='RheingoldGraph',
  full_name='rheingoldgraph.RheingoldGraph',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=286,
  serialized_end=458,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSummary',
    full_name='rheingoldgraph.RheingoldGraph.GetSummary',
    index=0,
    containing_service=None,
    input_type=_SUMMARYREQUEST,
    output_type=_GRAPHSUMMARY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayableLine',
    full_name='rheingoldgraph.RheingoldGraph.GetPlayableLine',
    index=1,
    containing_service=None,
    input_type=_LINEREQUEST,
    output_type=music__pb2._NOTE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RHEINGOLDGRAPH)

DESCRIPTOR.services_by_name['RheingoldGraph'] = _RHEINGOLDGRAPH

# @@protoc_insertion_point(module_scope)
